
[package]
name = "aviator5g-common"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version="0.4.19", features=["serde"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
